name: pop-dev
services:
    pop-server:
        container_name: "${COMPOSE_PROJECT_NAME}-server"
        extends:
          file: compose.prod.yml
          service: pop-server
        build:
          target: development     
        volumes:
          - ./pop-server:/app/src
          - pop_dev_static_volume:/app/static
          - pop_dev_media_volume:/app/media
          - pop_dev_logs_volume:/app/logs


    pop-client:
        container_name: "${COMPOSE_PROJECT_NAME}-client"
        extends:
          file: compose.prod.yml
          service: pop-client
        build:
          target: development
        volumes:
          - ./pop-client/src/app:/app/src/app
          - ./pop-client/src/assets:/app/src/assets
          - ./pop-client/openapi.json:/app/openapi.json
          - ${CLIENT_PLUGINS_PATH:-./pop-client/src/plugins}:/app/src/plugins

    pop-docs:
        container_name: "${COMPOSE_PROJECT_NAME}-docs"
        extends:
          file: compose.prod.yml
          service: pop-docs
        build:
          target: development
        volumes:
          - ./pop-docs:/app/src		
          - ./pop-server:/app/server		

    pop-nginx:
        image: nginx:1.23        
        container_name: "${COMPOSE_PROJECT_NAME}-nginx"
        extends:
          file: compose.prod.yml
          service: pop-nginx
        volumes:
          - ${POP_REVERSE_PROXY_SSL_CERTIFICATE_BUNDLE}:/etc/nginx/ssl/cert_host.pem
          - ${POP_REVERSE_PROXY_SSL_CERTIFICATE_PRIVATE_KEY}:/etc/nginx/ssl/cert_host.key      
          - pop_dev_static_volume:/app/static
          - pop_dev_media_volume:/app/media
          - pop_dev_logs_volume:/app/logs
        ports:
            - "${POP_REVERSE_PROXY_HTTPS_PORT:-443}:443"
            - "${POP_REVERSE_PROXY_HTTP_PORT:-80}:80"

    pop-postgres:
        image: postgres:13-alpine
        container_name: "${COMPOSE_PROJECT_NAME}-postgres"
        extends:
          file: compose.prod.yml
          service: pop-postgres   
        volumes:
            - pop_dev_postgres_volume:/var/lib/postgresql/data/


volumes:
    pop_dev_postgres_volume:
    pop_dev_media_volume:
    pop_dev_static_volume:
    pop_dev_logs_volume: