name: onconova-dev
services:
    server:
        container_name: "${COMPOSE_PROJECT_NAME}-server"
        extends:
          file: compose.prod.yml
          service: server
        build:
          target: development     
        volumes:
          - ./onconova-server:/app/src

    client:
        container_name: "${COMPOSE_PROJECT_NAME}-client"
        extends:
          file: compose.prod.yml
          service: client
        build:
          target: development
        volumes:
          - ./onconova-client/src/app:/app/src/app
          - ./onconova-client/src/assets:/app/src/assets
          - ${ONCONOVA_CLIENT_PLUGINS_PATH:-./onconova-client/src/plugins}:/app/src/plugins

    docs:
        container_name: "${COMPOSE_PROJECT_NAME}-docs"
        extends:
          file: compose.prod.yml
          service: docs
        build:
          target: development
        volumes:
          - ./onconova-docs:/app/src		
          - ./onconova-server:/app/server		

    reverse-proxy:
        image: nginx:1.23        
        container_name: "${COMPOSE_PROJECT_NAME}-nginx"
        extends:
          file: compose.prod.yml
          service: reverse-proxy

    database:
        image: postgres:13-alpine
        container_name: "${COMPOSE_PROJECT_NAME}-postgres"
        extends:
          file: compose.prod.yml
          service: database
        volumes:
            - postgresql-data:/var/lib/postgresql/data/

volumes:
    postgresql-data: