services:
    pop-server:
        container_name: "${COMPOSE_PROJECT_NAME}-server"
        restart: unless-stopped
        build:
            context: pop-server
            dockerfile: Dockerfile
            target: production      
        expose:
            - 8000
        volumes:
            - ./pop-server:/app/src
            - pop_static_volume:/app/static
            - pop_media_volume:/app/media
            - pop_logs_volume:/app/logs
        env_file: .env
        depends_on:
            - pop-postgres

    pop-client:
        container_name: "${COMPOSE_PROJECT_NAME}-client"
        restart: unless-stopped
        build:
            context: pop-client
            dockerfile: Dockerfile
            target: production
        volumes:
            - ${CLIENT_PLUGINS_PATH}:/app/src/plugins

    pop-docs:
        container_name: "${COMPOSE_PROJECT_NAME}-docs"
        restart: unless-stopped
        build:
            context: pop-docs
            dockerfile: Dockerfile
            target: production     

    pop-nginx:
        image: nginx:1.23        
        container_name: "${COMPOSE_PROJECT_NAME}-nginx"
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ${HOST_SSL_CERTIFICATE_BUNDLE}:/etc/nginx/ssl/cert_host.pem
            - ${HOST_SSL_CERTIFICATE_PRIVATE_KEY}:/etc/nginx/ssl/cert_host.key      
            - pop_static_volume:/app/static
            - pop_media_volume:/app/media
            - pop_logs_volume:/app/logs
        expose:
            - 80
            - 443
        ports:
            - "${WEBAPP_HTTPS_PORT:-443}:443"
            - "${WEBAPP_HTTP_PORT:-80}:80"
        env_file: .env
        depends_on:
            - pop-postgres
            - pop-server
            - pop-client
            - pop-docs

    pop-postgres:
        image: postgres:13-alpine
        container_name: "${COMPOSE_PROJECT_NAME}-postgres"
        restart: unless-stopped
        volumes:
            - pop_postgres_volume:/var/lib/postgresql/data/
        env_file: .env
        environment:
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - PGPORT=${POSTGRES_PORT}
        expose:
            - ${POSTGRES_PORT}
        ports:
            - ${POSTGRES_PORT}
        command: 
            - -p ${POSTGRES_PORT}      


volumes:
    pop_postgres_volume:
    pop_media_volume:
    pop_static_volume:
    pop_logs_volume: