#
name: Build & Push Docker Images on Release

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image
        id: server_push
        uses: docker/build-push-action@v6
        with:
          context: server 
          push: true
          build-contexts: |
            certificates=./certificates
          tags: ghcr.io/${{ env.REPOSITORY }}/server:${{ env.RELEASE_TAG }}

      - name: Build and push client image
        id: client_push
        uses: docker/build-push-action@v6
        with:
          context: client 
          push: true
          build-contexts: |
            plugins=./client/src/plugins
            certificates=./certificates
          tags: ghcr.io/${{ env.REPOSITORY }}/client:${{ env.RELEASE_TAG }}
