name: POP Client CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'pop-client/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: 'compose.dev.yml'
      COMPOSE_PROJECT_NAME: 'pop-ci'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Create .env file 
        uses: iamsauravsharma/create-dotenv@v3.2.0
        with:
          input-prefix: 'POP_'
        env:
          POP_POSTGRES_DATABASE: 'pop-ci-db'
          POP_POSTGRES_PORT: 5435
          POP_POSTGRES_USER: 'postgres'
          POP_POSTGRES_PASSWORD: 'postgres_secret'
          POP_POSTGRES_HOST: 'pop-postgres'
          POP_SERVER_ANONYMIZATION_KEY: 'anonymization_secret_key'
          POP_SERVER_ALLOWED_HOSTS: 'localhost'
          POP_SERVER_CORS_ALLOWED_ORIGINS: 'https://localhost'
          POP_SERVER_ENCRYPTION_KEY: 'django_secret_key'
          POP_HOSTING_ORGANIZATION: 'Organization Name' 
          POP_REVERSE_PROXY_SSL_CERTIFICATE_BUNDLE: '/etc/ssl/cert.pem'
          POP_REVERSE_PROXY_SSL_CERTIFICATE_PRIVATE_KEY: '/etc/ssl/cert.key'
          POP_CLIENT_PLUGINS_PATH: './pop-client/src/plugins'
          

      - name: Build pop-client service
        run: docker compose build pop-client

      - name: Run tests with pytest
        run: docker compose run --rm pop-client npm run test:ci