name: POP Client CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'pop-client/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: 'compose.dev.yml'
      COMPOSE_PROJECT_NAME: 'pop-ci'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Create .env file 
        uses: iamsauravsharma/create-dotenv@v3.2.0
        with:
          input-prefix: 'ENV_'
        env:
          ENV_POP_POSTGRES_DATABASE: 'pop-ci-db'
          ENV_POP_POSTGRES_PORT: 5435
          ENV_POP_POSTGRES_USER: 'postgres'
          ENV_POP_POSTGRES_PASSWORD: 'postgres_secret'
          ENV_POP_POSTGRES_HOST: 'database'
          ENV_POP_SERVER_ANONYMIZATION_KEY: 'anonymization_secret_key'
          ENV_POP_SERVER_ALLOWED_HOSTS: 'localhost'
          ENV_POP_SERVER_CORS_ALLOWED_ORIGINS: 'https://localhost'
          ENV_POP_SERVER_ENCRYPTION_KEY: 'django_secret_key'
          ENV_POP_HOSTING_ORGANIZATION: 'Organization Name' 
          ENV_POP_REVERSE_PROXY_SSL_CERTIFICATE_BUNDLE: '/etc/ssl/cert.pem'
          ENV_POP_REVERSE_PROXY_SSL_CERTIFICATE_PRIVATE_KEY: '/etc/ssl/cert.key'
          ENV_POP_CLIENT_PLUGINS_PATH: './pop-client/src/plugins'
          

      - name: Build client service
        run: docker compose build client

      - name: Run tests with pytest
        run: docker compose run --rm client npm run test:ci